import Head from 'next/head';
import { ReactElement } from 'react';
import MainLayout from '@/layouts/MainLayout';
import { Typography } from '@mui/material';
import CarouselComponent from '@/components/carousel/CarouselComponent';

export default function Home() {
  return (
    <>
      <Typography variant="h5" color="text.primary">
        hello world | home page
        <CarouselComponent />
      </Typography>
    </>
  );
}

Home.getLayout = (page: ReactElement) => {
  return (
    <>
      <Head>
        <title>App | Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>{page}</MainLayout>
    </>
  );
};
